#!/usr/bin/env bash
# Usage: workpile report [<level>]
# Summary: Report the current task later on the workpile
# Help: This will report the current task later on the workpile.
#
# <level>	indicates how much to report the current task back [default: 1]

# IMPORTS
########################################

. "$_WORKPILE_ROOT/lib/workpile.ini"

. "$_WORKPILE_ROOT/lib/generic.cst"
. "$_WORKPILE_ROOT/lib/workpile.cst"
. "$_WORKPILE_ROOT/lib/workpile.fun"

# SCRIPT
########################################

reportlevel="$1"

[ -n "$reportlevel" ] || reportlevel=1

task="$( wp_get_firsttask )"
tasknext="$( wp_get_tasknext "$task" )"

if [ -z "$tasknext" ]; then
	echo -e "No task following '${TAG_B}$( wp_get_taskname "$task" )${TAG_E}'\n${TAG_L}${CLR_FG_RED}You can't procrastinate forever !${TAG_E}"
	wp_exit "$WP_RV_NOTHINGTODO"
fi

# Reset first task
wp_set_firsttask "$tasknext"

wp_move_task "$task" "$reportlevel"

# Reset last task if needed
[ -z "$( wp_get_tasknext "$task" )" ] && wp_set_lasttask "$task"

# Infos
wp_addinfo_taskbg "$task"
wp_addinfo_taskfg "$tasknext"

# UI
echo -e "Reporting '${TAG_B}$( wp_get_taskname "$task" )${TAG_E}'. Current task is now '${TAG_B}$( wp_get_taskname "$tasknext" )${TAG_E}'."

# Exit
wp_exit "$WP_RV_OK"
