#!/usr/bin/env bash
# Usage: workpile list
# Summary: List the task pile
# Help: This will print a formatted pile of tasks.

# IMPORTS
########################################

. "$_WORKPILE_ROOT/lib/workpile.ini"

. "$_WORKPILE_ROOT/lib/generic.cst"
. "$_WORKPILE_ROOT/lib/workpile.cst"
. "$_WORKPILE_ROOT/lib/workpile.fun"

# SCRIPT
########################################

task="$( wp_get_lasttask )"
firsttask="$( wp_get_firsttask )"

while [ -n "$task" ]; do
	if [ "$task" = "$firsttask" ]; then
		echo -e "${TAG_BOLD} [ $( wp_get_taskname "$task" ) ] ${TAG_END}"
	else
		echo "$( wp_get_taskname "$task" )"
	fi

	task="$( wp_get_taskprev "$task" )"
done

# Exit
wp_exit "$WP_RV_OK"
