#!/usr/bin/env bash
# Usage: workpile pop
# Summary: Pop a task from the pile
# Help: This will pop a tasks from the pile and consider it done.

# IMPORTS
########################################

. "$_WORKPILE_ROOT/lib/workpile.ini"

. "$_WORKPILE_ROOT/lib/generic.cst"
. "$_WORKPILE_ROOT/lib/workpile.cst"
. "$_WORKPILE_ROOT/lib/workpile.fun"

# SCRIPT
########################################

task="$( wp_get_firsttask )"
taskname="$( wp_get_taskname "$task" )"

[ -z "$task" ] && wp_exit "$WP_RV_OK"

# Check if theres 0, 1 or more tasks
if [ "$task" = "$( wp_get_lasttask )" ]; then
	wp_clean_list
	echo -e "Popping '${TAG_B}${TAG_S}$taskname${TAG_E}'\n${TAG_L}No more task on workpile ! Good job !${TAG_E}"
	wp_exit "$WP_RV_OK"
fi

# Poping task
wp_set_firsttask "$( wp_get_tasknext "$task" )"

# User infos
echo -e "Popping '${TAG_B}${TAG_S}$taskname${TAG_E}' ! Next task is '${TAG_B}$( wp_get_taskname "$( wp_get_firsttask )" )${TAG_E}'"

# Exit
wp_exit "$WP_RV_OK"
